quarkus:
  datasource:
    db-kind: mysql
  live-reload:
      instrumentation: true
  application:
      name: ckm-gallery-service
  http:
      cors: true
      port: 8081
  hibernate-orm:
    database:
      generation: update
