server.port: 8081
spring:
    application:
        name: ckm-gallery-service
    jpa.hibernate:
        ddl-auto: update
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ckm-gallery
        username: ckm-admin
        password: cHV8MGd!E&XPvfHfDzK2
        driver-class-name: com.mysql.cj.jdbc.Driver
#    security:
#        oauth2:
#            resourceserver:
#                jwt:
#                    issuer-uri: http://${KEYCLOAK_HOST:localhost}:8180/auth/realms/ckm
#                    jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:8180/auth/realms/ckm/protocol/openid-connect/certs
